"""add_todolist_collaborators_table

Revision ID: 96d92ddf2686
Revises: 86f2dc5a531b
Create Date: 2026-03-12 00:13:29.897952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d92ddf2686'
down_revision: Union[str, Sequence[str], None] = '86f2dc5a531b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist_collaborators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('todolist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('invited_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', name='collaboratorstatus'), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['todolist_id'], ['todolists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todolist_collaborators_id'), 'todolist_collaborators', ['id'], unique=False)
    op.create_index(op.f('ix_todolist_collaborators_invited_email'), 'todolist_collaborators', ['invited_email'], unique=False)
    op.create_index(op.f('ix_todolist_collaborators_todolist_id'), 'todolist_collaborators', ['todolist_id'], unique=False)
    op.create_index(op.f('ix_todolist_collaborators_user_id'), 'todolist_collaborators', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todolist_collaborators_user_id'), table_name='todolist_collaborators')
    op.drop_index(op.f('ix_todolist_collaborators_todolist_id'), table_name='todolist_collaborators')
    op.drop_index(op.f('ix_todolist_collaborators_invited_email'), table_name='todolist_collaborators')
    op.drop_index(op.f('ix_todolist_collaborators_id'), table_name='todolist_collaborators')
    op.drop_table('todolist_collaborators')
    # ### end Alembic commands ###
